In [1]:
import numpy as np

def hebbian_learning_rule(input_pattern, weight_matrix):
    return weight_matrix + np.outer(input_pattern, input_pattern)

In [2]:
def perceptron_learning_rule(input_pattern, target, weight_vector, learning_rate):
    prediction = np.dot(weight_vector,input_pattern)
    error = target-prediction
    return weight_vector+learning_rate*error*input_pattern

In [3]:
def delta_learning_rule(input_pattern, target, weight_matrix, learning_rate):
    prediction = np.dot(weight_matrix, input_pattern)
    error = target - prediction
    return weight_matrix + learning_rate*error*input_pattern

In [11]:
def correlation_learning_rule(input_pattern, weight_matrix):
    return weight_matrix+np.outer(input_pattern, input_pattern)

def out_star_learning_rule(input_pattern, weight_matrix, learning_rate):
    return weight_matrix + learning_rate*np.outer(input_pattern,input_pattern)

In [12]:
input_size = 3
hebbian_weights = np.random.rand(input_size, input_size)
perceptron_weights = np.random.rand(input_size)
delta_weights = np.random.rand(input_size, input_size)
correlation_weights = np.random.rand(input_size, input_size)
out_star_weights = np.random.rand(input_size,input_size)
print("\n")
print(hebbian_weights)
print("\n")
print(perceptron_weights)
print("\n")
print(delta_weights)
print("\n")
print(correlation_weights)
print("\n")
print(out_star_weights)
print("\n")



[[0.51359718 0.43827307 0.96263276]
 [0.60134248 0.9443014  0.44131815]
 [0.12156072 0.44360268 0.61077013]]


[0.88455759 0.50637115 0.22248692]


[[0.58119623 0.87071805 0.4379669 ]
 [0.2995975  0.92872    0.79243131]
 [0.74733134 0.48300108 0.83450074]]


[[0.75563647 0.64354957 0.73638128]
 [0.18998525 0.39949435 0.89658666]
 [0.4476257  0.07775571 0.17745207]]


[[0.33876448 0.73666726 0.56153316]
 [0.39361405 0.29784293 0.98275428]
 [0.13781052 0.38535959 0.42893106]]




In [13]:
input_pattern = np.array([0.2,0.5,0.8])
target = 1

hebbian_update = hebbian_learning_rule(input_pattern, hebbian_weights)
perceptron_update = perceptron_learning_rule(input_pattern, target, perceptron_weights, learning_rate=0.1)
delta_update = delta_learning_rule(input_pattern, target, delta_weights, learning_rate=0.1)
correlation_update = correlation_learning_rule(input_pattern, correlation_weights)
out_star_update = out_star_learning_rule(input_pattern, out_star_weights, learning_rate=0.1)


In [14]:
print("\n")
print(hebbian_update)
print("\n")
print(perceptron_update)
print("\n")
print(delta_update)
print("\n")
print(correlation_update)
print("\n")
print(out_star_update)
print("\n")



[[0.55359718 0.53827307 1.12263276]
 [0.70134248 1.1943014  0.84131815]
 [0.28156072 0.84360268 1.25077013]]


[0.89239586 0.52596682 0.25383999]


[[0.5831568  0.86280682 0.43328151]
 [0.30155807 0.92080877 0.78774591]
 [0.7492919  0.47508985 0.82981535]]


[[0.79563647 0.74354957 0.89638128]
 [0.28998525 0.64949435 1.29658666]
 [0.6076257  0.47775571 0.81745207]]


[[0.34276448 0.74666726 0.57753316]
 [0.40361405 0.32284293 1.02275428]
 [0.15381052 0.42535959 0.49293106]]


